config/routes.rb
Rails.application.routes.draw do
  get 'journalists/index'
  get 'journalists/new'
  get 'posts/index'
  get 'posts/new'
  post 'posts',     to:"posts#create"
  post 'journalists',       to:"journalists#create"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/journalist.rb
class Journalist < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/journalists_controller.rb
class JournalistsController < ApplicationController
  def index
    @journalists = Journalist.all
  end

  def new
    @journalist = Journalist.new
  end

  def create
    @journalist = Journalist.new(journalist_params)

    if @journalist.save
        redirect_to journalists_index_path
    else
      render :new
    end
  end

  private

  def journalist_params
    params.require(:journalist).permit(:name, :lastname, :speciality)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
      @post = Post.new(post_params)

      if @post.save
        redirect_to posts_index_path
      else
        render :new
      end
  end

  private

  def post_params
    params.require(:post).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/journalists_helper.rb
module JournalistsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/journalists/index.html.erb
<h1>Mostrando Periodistas</h1>
<p>cantidad: <%= @journalists.count %></p>

<% @journalists.each do |journalist| %>
    <h2><%= journalist.name %> <%= journalist.lastname %></h2>
    <p><%= journalist.speciality %></p>
<% end %>

<div class="text-center my-5">
    <%= link_to "Crear otro", journalists_new_path, class:"btn btn-dark" %>
</div>

app/views/journalists/new.html.erb
<h1 class="text-center my-5">Agregar Periodistas</h1>
<br><br>


<div class="d-flex justify-content-center">
    <div class="card col-6 ">
        <%= form_with model: @journalist, method: :post do |form| %>
            <div class="border p-5 shadow ">
                <div class="mb-3">
                    <%= form.label :name, "Nombre del periodista", class:"form-label" %>
                    <%= form.text_field :name, class:"form-control" %>
                </div>
                <div class="mb-3">
                    <%= form.label :lastname, "Apellido", class:"form-label" %>
                    <%= form.text_field :lastname, class:"form-control" %>
                </div>
                <div class="mb-5">
                    <%= form.label :speciality, "Especialidad", class:"form-label" %>
                    <%= form.text_area :speciality, class:"form-control" %>
                </div>
                <div class="text-center">
                    <%= form.submit "Agregar", class:"btn btn-dark" %>
                </div>
            </div>
        <% end %>
    </div>
</div>
<div class="text-center my-5">
    <%= link_to "Listado", journalists_index_path, class:"btn btn-dark" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BasicForm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
  </body>
</html>

app/views/posts/index.html.erb
<h1>Mostrando weas</h1>
<p>cantidad: <%= @posts.count %></p>

<% @posts.each do |post| %>
    <h2><%= post.title %></h2>
    <p><%= post.content %></p>
<% end %>

<div class="text-center my-5">
    <%= link_to "Crear otro", posts_new_path, class:"btn btn-dark" %>
</div>

app/views/posts/new.html.erb
<h1 class="text-center my-5">Crear Post</h1>
<br><br>


<div class="d-flex justify-content-center">
    <div class="card col-6 ">
        <%= form_with model: @post, method: :post do |form| %>
            <div class="border p-5 shadow ">
                <div class="mb-3">
                    <%= form.label :title, "Título del post", class:"form-label" %>
                    <%= form.text_field :title, class:"form-control" %>
                </div>
                <div class="mb-5">
                    <%= form.label :content, "Contenido", class:"form-label" %>
                    <%= form.text_area :content, class:"form-control" %>
                </div>
                <div class="text-center">
                    <%= form.submit "Enviar", class:"btn btn-dark" %>
                </div>
            </div>
        <% end %>
    </div>
</div>
<div class="text-center my-5">
    <%= link_to "Listado", root_path, class:"btn btn-dark" %>
</div>